---
- name: install python-virtualenv python-dev python-tk
  apt: 
    name: ['python-virtualenv', 'python-dev', 'python-tk']
    state: present

- name: add user deezer
  user:
      name: deezer

- name: add group deezer
  group:
      name: deezer

- name: clone deezer repo
  git:
      repo: https://github.com/kmille/deezer-downloader.git
      dest: /opt/deezer
      force: true

- name: "chown deezer to /opt/deezer"
  file: 
    dest: /opt/deezer
    owner: deezer
    group: deezer
    mode: 0755
    recurse: yes

- name: install pip requirements in virtualenv
  pip:
    requirements: /opt/deezer/requirements.txt
    virtualenv: /opt/deezer/venv

- name: add service file for deezer
  copy:
      src: deezer.service
      dest: /etc/systemd/system/deezer.service

- name: create download dir
  file:
      path: "{{ deezer_download_dir }}"
      mode: 0755
      owner: deezer
      group: deezer
      state: directory

- name: start deezer service 
  service:
      name: deezer
      state: restarted
      enabled: true

- name: fix url /deezer/ prefix from reverse proxy in app settings.py
  shell: sed -i 's@url_prefix = "/"@url_prefix = "/deezer/"@' /opt/deezer/app/settings.py

- name: set update_mpd preference in app settings.py
  shell: sed -i 's@update_mpd = False@update_mpd = True@' /opt/deezer/app/settings.py

- name: install nginx
  apt:
      name: nginx
      state: present

- name: add nginx config
  copy:
      dest: /etc/nginx/sites-enabled/default
      src: nginx.conf

- name: restart nginx
  service:
      name: nginx
      state: restarted

